### ISSUE TITLE
Messages for multi-configuration project not useful

### ISSUE THREAD

**Issue by lubomir** [fedora-infra/jenkins-fedmsg-emit#3]
If a Jenkins project has multiple configuration, the message that gets sent contains name of the configuration, but no details about the project.

[This message](https://apps.fedoraproject.org/datagrepper/id?id=2016-ef190673-90c3-4947-b82f-a909d870d53f&is_raw=true&size=extra-large) has no indication it belongs to [this project](http://jenkins.fedorainfracloud.org/job/fedpkg/).

**Comment by relrod** [comment]
Example of fixed message: https://apps.fedoraproject.org/datagrepper/id?id=2016-ed81db5e-9b7e-4dc7-b752-ba48a506b214&is_raw=true&size=extra-large

**Comment by lubomir** [comment]
That looks perfect. Thank you very much.
